"use client";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import type { Project } from "@/lib/projects";

function Media({ project, section, paired = false }: { project: Project; section?: "method" | "results"; paired?: boolean }) {
  return <div className={paired ? "project-media calibration-pair" : "project-media"}>{project.media?.filter(m => !section || m.section === section).map(m => <figure key={m.src} className={m.photo ? "media-figure photo-figure" : "media-figure"}><div className="media-image"><img src={m.src} alt={m.alt} loading="lazy" /></div><figcaption>{m.caption}</figcaption></figure>)}</div>;
}
function Results({ p }: { p: Project }) {
  if (p.slug === "zero-shot-navigation") return <div className="benchmark"><h2>HM3D evaluation</h2>{[{label:"Success rate",value:55},{label:"SPL",value:33.7}].map(m => <div className="benchmark-row" key={m.label}><div><span>{m.label}</span><strong>{m.value.toFixed(1)}%</strong></div><div className="benchmark-track"><span style={{width:`${m.value}%`}} /></div></div>)}<p className="benchmark-comparison"><strong>+3.3 percentage points</strong> SPL compared with VLFM</p></div>;
  if (p.slug === "vision-robot-calibration") return <div className="validation"><h2>Position validation</h2><p>A sample coordinate check from the robot experiments.</p><table><caption className="sr-only">Single position validation case</caption><thead><tr><th scope="col">Measurement</th><th scope="col">X</th><th scope="col">Y</th></tr></thead><tbody><tr><th scope="row">Target (approx.)</th><td>200</td><td>200</td></tr><tr><th scope="row">Reconstructed</th><td>197.59</td><td>202.58</td></tr><tr><th scope="row">Axis error</th><td>1.21%</td><td>1.29%</td></tr></tbody></table></div>;
  if (p.slug === "vpp-v2g") return <div className="energy-results"><h2>Modeled electricity transfer</h2><Media project={p} section="results"/><dl className="energy-notes"><div><dt>Incheon → Seoul</dt><dd><strong>47.53 MW</strong> estimated capacity from commuting EVs.</dd></div><div><dt>Daily redistribution</dt><dd><strong>41.89 MWh</strong> across the modeled Incheon, Chungnam and Seoul routes.</dd></div><div><dt>Seoul summer peak</dt><dd><strong>17.3 MW</strong> reduction in the simulation.</dd></div></dl></div>;
  return <div className="storybook-results"><div className="award-line"><span aria-hidden="true">★</span><div><strong>Silver prize · 3rd place</strong><p>2024 AI Convergence Industry-Academia Hackathon</p></div></div><h2>Prototype & character consistency</h2><p>The prototype generated a personalized story and illustrated scenes from user inputs. During testing, the same character sometimes appeared differently across scenes.</p><Media project={p} section="results" /></div>;
}
export function ProjectDetails({ project: p }: { project: Project }) {
  return <><Tabs defaultValue="contribution" className="detail-tabs">
    <TabsList aria-label="Project details"><TabsTrigger value="contribution">My contribution</TabsTrigger><TabsTrigger value="method">Method</TabsTrigger><TabsTrigger value="results">Results & limits</TabsTrigger></TabsList>
    <TabsContent value="contribution"><div className="detail-tab-grid"><div><h2>My role</h2>{p.contributions.map((c,i) => <div className="contribution-row" key={c.title}><span className="step-number">0{i+1}</span><div><h3>{c.title}</h3><p>{c.body}</p></div></div>)}</div><aside className="context-box"><h3>Project context</h3><p>{p.context}</p></aside></div></TabsContent>
    <TabsContent value="method"><div className="detail-tab-grid"><div><h2>Method</h2>{p.methods.map((m,i) => <div className="contribution-row" key={m.title}><span className="step-number">0{i+1}</span><div><h3>{m.title}</h3><p>{m.body}</p></div></div>)}</div><aside className="context-box"><h3>Tools & methods</h3><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div></aside></div>{p.slug !== "vision-robot-calibration" && <Media project={p} section="method" />}</TabsContent>
    <TabsContent value="results"><Results p={p}/><p className="result-note">{p.resultNote}</p><div className="limits"><h3>{p.slug === "zero-shot-navigation" ? "Evaluation setup" : "Discussion"}</h3><p>{p.limitation}</p></div></TabsContent>
  </Tabs>{p.slug === "vision-robot-calibration" && <section className="experiment-pair"><h2>Experiment setup & measurement</h2><Media project={p} paired /></section>}</>;
}
